apiVersion: v1
kind: Service
metadata:
  name: loco-service
  namespace: loco-application
spec:
  type: NodePort
  selector:
    app: loco-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
