apiVersion: v1
kind: Service
metadata:
  name: loco-app
  namespace: loco-app 
spec:
  type: NodePort #NodePort exposes the service on each node's IP at a static port (nodePort).
  selector:
    app: loco-app
  ports:
    - protocol: TCP
      port: 80   #pods connect to this service, they will use this port.
      targetPort: 3000 #when traffic is sent to port 80 of the service, it will be directed to port 3000 on the selected pods.
      nodePort: 31516   #can be accessed externally on port 31516 of any node in the cluster.
